### PR TITLE
Add settings for debugging compilations

### PR DESCRIPTION
**Pull request by uekann**
F5 debugging is possible by creating the file to be compiled under the "sample-for-debug" directory and entering that file when debugging.

### CODE REVIEW

**Comment by momeemt** [comment]
@uekann What VSCode extension or software do I need for debugging? I cannot debug even though I have lanza.lldb-vscode and llvm installed. VSCode says "Configured debug type 'lldb' is not supported".

**Comment by uekann** [comment]
I'm using the extension "vadimcn.vscode-lldb".
I've added it to extensions.json and committed it.

**Comment by momeemt** [comment]
Thanks! I succeeded in debugging.

**Review by momeemt — APPROVED** [review]
LGTM!

**Pull request merged**
